spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

  datasource:
    url: ${MYSQL8_JDBC_URL}
    username: ${MYSQL8_USERNAME}
    password: ${MYSQL8_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: ${REDIS6_HOST}
    port: ${REDIS6_PORT}

logging:
  level:
    org:
      springframework:
        web: WARN

    com:
      support:
        notice: INFO

      hibernate: WARN

  file:
    path: ./logs
    name: rsupport-notice-api.log
