spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

  datasource:
    url: ${MYSQL8_JDBC_TEST_URL}
    username: ${MYSQL8_TEST_USERNAME}
    password: ${MYSQL8_TEST_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

JWT_SECRET: JWT_SECRET_VALUE