spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/rsupport
    username: noticemanager
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

